### ISSUE TITLE
Sharing iP code quality feedback [for @francisyzy]

### ISSUE THREAD

**Issue by soc-se-bot-red** [francisyzy/ip#17]
@francisyzy We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

Example from [`src/main/java/duke/Storage.java` lines `20-20`](https://github.com/francisyzy/ip/blob/c2f887023075614b60aa9d9b5f7111b8d3a74aa6/src/main/java/duke/Storage.java#L20..L20):

```java

    // private final String filePath;

```

Example from [`src/main/java/duke/Storage.java` lines `22-22`](https://github.com/francisyzy/ip/blob/c2f887023075614b60aa9d9b5f7111b8d3a74aa6/src/main/java/duke/Storage.java#L22..L22):

```java

    // Storage(String filePath) {

```

Example from [`src/main/java/duke/Storage.java` lines `23-23`](https://github.com/francisyzy/ip/blob/c2f887023075614b60aa9d9b5f7111b8d3a74aa6/src/main/java/duke/Storage.java#L23..L23):

```java

    // this.filePath = filePath;

``` 

**Suggestion:** Remove dead code from the codebase.

### Aspect: Method Length

Example from [`src/main/java/duke/Parser.java` lines `34-76`](https://github.com/francisyzy/ip/blob/c2f887023075614b60aa9d9b5f7111b8d3a74aa6/src/main/java/duke/Parser.java#L34..L76):

```java

    public static Command parse(String input) throws DukeException {
        switch (input) {
        case "list":
            return new ListCommand();
        case "clear":
            return new ClearCommand();
        case "bye":
        case "exit":
            return new ExitCommand();
        default:
            // Have to do it at the starts with because what if "todo mark this as done"
            if (input.startsWith(Commands.MARK.cmd())) {
                int[] taskNumbers = subtractInt(getNumbers(input), 1);
                return new MarkCommand(taskNumbers);
            } else if (input.startsWith(Commands.UNMARK.cmd())) {
                int[] taskNumbers = subtractInt(getNumbers(input), 1);
                return new UnmarkCommand(taskNumbers);
            } else if (input.startsWith(Commands.TODO.cmd())) {
                String[] parsed = handleTask(input);
                String title = parsed[0];
                return new TodoCommand(title);
            } else if (input.startsWith(Commands.DEADLINE.cmd())) {
                String[] parsed = handleTask(input);
                String title = parsed[0];
                String deadline = parsed[1];
                return new DeadlineCommand(title, deadline);
            } else if (input.startsWith(Commands.EVENT.cmd())) {
                String[] parsed = handleTask(input);
                String title = parsed[0];
                String from = parsed[1];
                String to = parsed[2];
                return new EventCommand(title, from, to);
            } else if (input.startsWith(Commands.DEL.cmd())) {
                int[] taskNumbers = subtractInt(getNumbers(input), 1);
                return new DeleteCommand(taskNumbers);
            } else if (input.startsWith(Commands.FIND.cmd())) {
                String query = input.substring(Commands.FIND.len());
                return new FindCommand(query);
            } else {
                throw new DukeException(Views.UNKNOWN_CMD_ERR_STRING.eng());
            }
        }
    }

```

Example from [`src/main/java/duke/Storage.java` lines `56-93`](https://github.com/francisyzy/ip/blob/c2f887023075614b60aa9d9b5f7111b8d3a74aa6/src/main/java/duke/Storage.java#L56..L93):

```java

    public ArrayList<Task> load() throws DukeException {
        ArrayList<Task> tasksList = new ArrayList<Task>(100);
        try {
            Scanner scanner = new Scanner(new File("duke_data.txt"));
            while (scanner.hasNext()) {
                String line = scanner.nextLine();
                boolean isDone = line.indexOf("[X]") == -1 ? false : true;
                line = line.replace("[ ]", "");
                line = line.replace("[X]", "");
                String[] parsed = Parser.handleTask(line);
                if (line.startsWith(Commands.TODO.cmd())) {
                    String title = parsed[0];
                    Task newTask = new Todo(title, isDone);
                    tasksList.add(newTask);
                } else if (line.startsWith(Commands.DEADLINE.cmd())) {
                    String title = parsed[0];
                    String deadline = parsed[1];
                    Task newTask = new Deadline(title, deadline, isDone);
                    tasksList.add(newTask);
                } else if (line.startsWith(Commands.EVENT.cmd())) {
                    String title = parsed[0];
                    String from = parsed[1];
                    String to = parsed[2];
                    Task newTask = new Event(title, from, to, isDone);
                    tasksList.add(newTask);
                } else {
                    throw new DukeException(Views.LOAD_EXTRA_ERR_STRING.eng());
                }
            }
            scanner.close();
        } catch (Exception e) {
            if (e instanceof DukeException) {
                throw new DukeException(e.getMessage());
            }
            // Silent fail if cannot load previous file
        }
        return tasksList;
    }

``` 

**Suggestion:** Consider applying [SLAP (and other abstraction mechanisms)](https://nus-cs2103-ay2223s2.github.io/website//se-book-adapted/chapters/codeQuality.html#guideline-maximise-readability) to shorten methods e.g., extract some code blocks into separate methods. You may ignore this suggestion if you think a longer method is justified in a particular case.

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/duke/Duke.java` lines `53-56`](https://github.com/francisyzy/ip/blob/c2f887023075614b60aa9d9b5f7111b8d3a74aa6/src/main/java/duke/Duke.java#L53..L56):

```java

    /**
     * Main method for running the text Version
     * @param args
     */

```

Example from [`src/main/java/duke/Duke.java` lines `62-65`](https://github.com/francisyzy/ip/blob/c2f887023075614b60aa9d9b5f7111b8d3a74aa6/src/main/java/duke/Duke.java#L62..L65):

```java

    /**
     * You should have your own function to generate a response to user input.
     * Replace this stub with your completed method.
     */

```

Example from [`src/main/java/duke/DukeException.java` lines `7-9`](https://github.com/francisyzy/ip/blob/c2f887023075614b60aa9d9b5f7111b8d3a74aa6/src/main/java/duke/DukeException.java#L7..L9):

```java

    /**
     * Default exception thrown
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message (Subject Only)

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by francisyzy** [comment]
K thanks
